project_id = "nesaccllkjgxhhqbfbho"

[functions.discogs-auth]
verify_jwt = false

[functions.discogs-collection]
verify_jwt = false

[functions.discogs-search]
verify_jwt = false

[functions.discogs-price]
verify_jwt = false

[functions.analyze-collection]
verify_jwt = false